# Generated by Django 6.0.5 on 2026-05-18 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='詳細・コメント')),
                ('recruit_type', models.CharField(choices=[('helper', '助っ人募集'), ('member', 'メンバー募集')], max_length=10, verbose_name='募集タイプ')),
                ('prefecture', models.CharField(choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], max_length=10, verbose_name='都道府県')),
                ('position', models.CharField(choices=[('投手', '投手（ピッチャー）'), ('捕手', '捕手（キャッチャー）'), ('一塁手', '一塁手（ファースト）'), ('二塁手', '二塁手（セカンド）'), ('三塁手', '三塁手（サード）'), ('遊撃手', '遊撃手（ショート）'), ('左翼手', '左翼手（レフト）'), ('中堅手', '中堅手（センター）'), ('右翼手', '右翼手（ライト）'), ('指名打者', '指名打者（DH）'), ('問わない', 'ポジション問わない')], default='問わない', max_length=10, verbose_name='希望ポジション')),
                ('level', models.CharField(choices=[('初心者', '初心者'), ('中級者', '中級者'), ('上級者', '上級者'), ('問わない', 'レベル問わない')], default='問わない', max_length=10, verbose_name='希望レベル')),
                ('date', models.DateField(blank=True, null=True, verbose_name='希望日')),
                ('is_active', models.BooleanField(default=True, verbose_name='募集中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruit_posts', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruit_posts', to='teams.team', verbose_name='募集チーム')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='メッセージ')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('accepted', '承認'), ('rejected', '却下')], default='pending', max_length=10, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruit_applications', to=settings.AUTH_USER_MODEL, verbose_name='応募者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.recruitpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('post', 'applicant')},
            },
        ),
    ]
