# Generated by Django 6.0.5 on 2026-05-18 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='グラウンド名')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('prefecture', models.CharField(choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], max_length=10, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='市区町村')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='緯度')),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='経度')),
                ('description', models.TextField(blank=True, verbose_name='説明・備考')),
                ('surface', models.CharField(choices=[('土', '土'), ('天然芝', '天然芝'), ('人工芝', '人工芝'), ('その他', 'その他')], default='土', max_length=10, verbose_name='グラウンド種別')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='収容人数')),
                ('fee', models.CharField(blank=True, max_length=100, verbose_name='使用料')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('website', models.URLField(blank=True, verbose_name='公式サイト')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_grounds', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
            ],
            options={
                'ordering': ['prefecture', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroundReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='予約日')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('is_shared', models.BooleanField(default=False, verbose_name='グラウンドをシェア可能')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='grounds.ground')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_reservations', to='teams.team', verbose_name='予約チーム')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
